name: "godot-ci export"
on: 
  push:
    branches: [ main ]

env:
  GODOT_VERSION: 3.4.5
  EXPORT_NAME: TheLegendOfLumberjack
  PROJECT_PATH: TheLegendOfLumberjack
  
jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p $PROJECT_PATH/build/windows
          cd $PROJECT_PATH
          godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: Create a Release of commit
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: windows-latest
          prerelease: false
          title: The Legend of lumberjack - windows
          files: |
             TheLegendOfLumberjack/build/windows/TheLegendOfLumberjack.exe
             
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p $PROJECT_PATH/build/linux
          cd $PROJECT_PATH
          godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: Create a Release of commit
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: linux-latest
          prerelease: false
          title: The Legend of lumberjack - linux
          files: |
             TheLegendOfLumberjack/build/linux/TheLegendOfLumberjack.x86_64

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p $PROJECT_PATH/build/web
          cd $PROJECT_PATH
          godot -v --export "HTML5" ./build/web/index.html
      - name: Create a Release of commit
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: web-latest
          prerelease: false
          title: The Legend of lumberjack - web
          files: |
             $PROJECT_PATH/build/web/index.html
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: TheLegendOfLumberjack/build/web # The folder the action should deploy.

  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p $PROJECT_PATH/build/mac
          cd $PROJECT_PATH
          godot -v --export "Mac OSX" ./build/mac/$EXPORT_NAME.zip      
      - name: Create a Release of commit
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: mac-latest
          prerelease: false
          title: The Legend of lumberjack - mac
          files: |
             TheLegendOfLumberjack/build/mac/TheLegendOfLumberjack.zip
          

